apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mssql-command-storage-claim
spec:
    accessModes:
      - ReadWriteOnce
    resources:
        requests:
            storage: 300Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: mssql-command-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mssql
    template:
        metadata:
            labels:
                app: mssql
        spec:
            containers:
              - name: mssql
                image: mcr.microsoft.com/mssql/server:2022-latest
                ports:
                  - containerPort: 1433
                    name: tcpsql
                env:
                  - name: MSSQL_PID
                    value: "Express"
                  - name: ACCEPT_EULA
                    value: "Y"
                  - name: MSSQL_SA_PASSWORD
                    valueFrom:
                        secretKeyRef:
                            name: mssql
                            key: MY_PASSWORD
                volumeMounts:
                  - name: mssqldb
                    mountPath: /var/opt/mssql/data
            volumes:
              - name: mssqldb
                persistentVolumeClaim:
                    claimName: mssql-command-storage-claim
---
apiVersion: v1
kind: Service
metadata:
    name: mssql-command-cluster-ip-service
spec:
    type: ClusterIP
    selector:
        app: mssql
    ports:
      - name: mssql
        protocol: TCP
        port: 31434
        targetPort: 1433
---
apiVersion: v1
kind: Service
metadata:
    name: mssql-command-load-balancer
spec:
    type: LoadBalancer
    selector:
        app: mssql
    ports:
      - protocol: TCP
        port: 31434
        targetPort: 1433