apiVersion: apps/v1
kind: Deployment
metadata:
    name: mssql-platform-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mssql
    template:
        metadata:
            labels:
                app: mssql
        spec:
            containers:
              - name: mssql
                image: mcr.microsoft.com/mssql/server:2022-latest
                ports:
                  - containerPort: 1433
                    name: tcpsql
                env:
                  - name: MSSQL_PID
                    value: "Express"
                  - name: ACCEPT_EULA
                    value: "Y"
                  - name: MSSQL_SA_PASSWORD
                    valueFrom:
                        secretKeyRef:
                            name: mssql
                            key: MY_PASSWORD
                volumeMounts:
                  - mountPath: /var/opt/mssql/data
                    name: mssqldb
            volumes:
              - name: mssqldb
                persistentVolumeClaim:
                    claimName: mssql-storage-claim