apiVersion: v1
kind: Service
metadata:
    name: command-cluster-ip-service
spec:
    type: ClusterIP
    selector:
        app: command-service-api
    ports:
      - name: command-service-api
        protocol: TCP
        port: 8080
        targetPort: 8080